name: Integracion Continua - Notificacion

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node app.js

      - name: Enviar notificacion
        run: |
          curl -H "Title: Push Detectado" \
               -H "Priority: high" \
               -d "Se realizo un push a la rama main." \
               https://ntfy.sh/devops-itla
